name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest

      - name: Install platform
        run: pio platform install atmelsam

      - name: Run PlatformIO_get_mac_12e
        run: pio run -e esp12e -d ./get_mac

      - name: Run PlatformIO_get_mac_32
        run: pio run -e lolin32_lite -d ./get_mac

      - name: Run PlatformIO_central_12e
        run: pio run -e esp12e -d ./ESP_8266_Arduino_FW/Central

      - name: Run PlatformIO_central_8266
        run: pio run -e esp12e -d ./ESP_8266_Arduino_FW/Central_broadcast

      - name: Run PlatformIO_central_8266
        run: pio run -e esp12e -d ./ESP_8266_Arduino_FW/Central_to_server

      - name: Run PlatformIO_slave_32
        run: pio run -e lolin32_lite -d ./ESP_32_Arduino_FW/slave

      - name: Run PlatformIO_p_p_sender_32
        run: pio run -e lolin32_lite -d ./ESP_32_Arduino_FW/point-point_sender

      - name: Run PlatformIO_p_p_recivevr_32
        run: pio run -e lolin32_lite -d ./ESP_32_Arduino_FW/point-point_receiver

      - name: Run PlatformIO_wrpper_p_p_recivevr_32
        run: pio run -e lolin32_lite -d ./Wrapper/point-point_receiver

      - name: Run PlatformIO_wrpper_p_p_recivevr_8266
        run: pio run -e esp12e -d ./Wrapper/point-point_receiver

      - name: Run PlatformIO_wrpper_p_p_sender_32
        run: pio run -e lolin32_lite -d ./Wrapper/point-point_sender

      - name: Run PlatformIO_wrpperr_p_p_sender_8266
        run: pio run -e esp12e -d ./Wrapper/point-point_sender

      - name: Run PlatformIO_server_32
        run: pio run -e denky32 -d ./ESP_32_Arduino_FW/web_server
